on:
  workflow_call:
    secrets:
      JFROG_ACCESS_TOKEN:
        required: true

jobs:
  publish_python_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: python -m pip install pip twine
      - name: Build package
        run: python -m build
      - name: Release
        run: twine upload dist/*
        env:
          TWINE_PASSWORD: ${{ secrets.JFROG_ACCESS_TOKEN }}
          TWINE_REPOSITORY: omnimod
          TWINE_USERNAME: __token__
